import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planoir</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Planoir home page
        </h1>

        <div className={styles.grid}>
          Cards
        </div>
      </main>

      <footer className={styles.footer}>
        <h3>Footer</h3>
      </footer>
    </div>
  )
}
